export const EXAMPLE_COLORS = {
  background: "#f3f7ff",
  surface: "#ffffff",
  surfaceMuted: "#eef4ff",
  border: "#d6e3ff",
  text: "#0b1424",
  textMuted: "#5a6d8f",
  accent: "#0ea5e9",
  accentSoft: "#dff4ff",
  accentDeep: "#0369a1",
  info: "#14b8a6",
  infoSoft: "#e6fffb",
  warning: "#f97316",
  danger: "#dc2626",
  dangerSoft: "#fef2f2",
  dangerBorder: "#fecaca",
} as const;
